import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { requireAuth } from "../middleware/auth.js";
const router=Router(); router.use(requireAuth);
const schema=z.object({title:z.string().min(2).max(180),description:z.string().max(1000).default(""),projectId:z.string().uuid(),assigneeId:z.string().uuid().nullable().optional(),status:z.enum(["TODO","IN_PROGRESS","DONE"]).default("TODO"),priority:z.enum(["LOW","MEDIUM","HIGH"]).default("MEDIUM"),dueDate:z.string().datetime().nullable().optional()});
const dateify=(v)=>({...v,...(Object.prototype.hasOwnProperty.call(v,"dueDate")?{dueDate:v.dueDate?new Date(v.dueDate):null}:{})});
async function owns(projectId,userId){return !!(await prisma.project.findFirst({where:{id:projectId,ownerId:userId}}));}
router.get("/",async(req,res,next)=>{try{const where={project:{ownerId:req.user.id}}; if(req.query.status)where.status=req.query.status; if(req.query.priority)where.priority=req.query.priority; if(req.query.projectId)where.projectId=req.query.projectId; if(req.query.q)where.OR=[{title:{contains:String(req.query.q),mode:"insensitive"}},{description:{contains:String(req.query.q),mode:"insensitive"}}]; res.json({success:true,data:await prisma.task.findMany({where,include:{project:true,assignee:true},orderBy:{updatedAt:"desc"}})});}catch(e){next(e);}});
router.post("/",async(req,res,next)=>{try{const p=schema.safeParse(req.body); if(!p.success)return res.status(400).json({success:false,error:{message:"Validation failed",details:p.error.flatten()}}); if(!(await owns(p.data.projectId,req.user.id)))return res.status(403).json({success:false,error:{message:"You do not own this project"}}); res.status(201).json({success:true,data:await prisma.task.create({data:dateify(p.data)})});}catch(e){next(e);}});
router.patch("/:id",async(req,res,next)=>{try{const p=schema.partial().refine(v=>Object.keys(v).length).safeParse(req.body); if(!p.success)return res.status(400).json({success:false,error:{message:"Validation failed",details:p.error.flatten()}}); const task=await prisma.task.findFirst({where:{id:req.params.id,project:{ownerId:req.user.id}}}); if(!task)return res.status(404).json({success:false,error:{message:"Task not found"}}); if(p.data.projectId && !(await owns(p.data.projectId,req.user.id)))return res.status(403).json({success:false,error:{message:"You do not own target project"}}); res.json({success:true,data:await prisma.task.update({where:{id:req.params.id},data:dateify(p.data)})});}catch(e){next(e);}});
router.delete("/:id",async(req,res,next)=>{try{const task=await prisma.task.findFirst({where:{id:req.params.id,project:{ownerId:req.user.id}}}); if(!task)return res.status(404).json({success:false,error:{message:"Task not found"}}); await prisma.task.delete({where:{id:task.id}}); res.status(204).send();}catch(e){next(e);}});
export default router;
