import { z } from "zod";
const params = z.object({ id: z.string().uuid() });
export const idSchema = z.object({ body: z.object({}), params, query: z.object({}) });
export const userCreateSchema = z.object({ body: z.object({ name: z.string().min(2).max(80), email: z.string().email(), role: z.string().min(2).max(80).default("Developer") }), params: z.object({}), query: z.object({}) });
export const userUpdateSchema = z.object({ body: z.object({ name: z.string().min(2).max(80).optional(), email: z.string().email().optional(), role: z.string().min(2).max(80).optional() }).refine(v => Object.keys(v).length), params, query: z.object({}) });
export const projectCreateSchema = z.object({ body: z.object({ name: z.string().min(2).max(120), description: z.string().max(500).default(""), ownerId: z.string().uuid() }), params: z.object({}), query: z.object({}) });
export const projectUpdateSchema = z.object({ body: z.object({ name: z.string().min(2).max(120).optional(), description: z.string().max(500).optional(), ownerId: z.string().uuid().optional() }).refine(v => Object.keys(v).length), params, query: z.object({}) });
export const taskCreateSchema = z.object({ body: z.object({ title: z.string().min(2).max(180), description: z.string().max(1000).default(""), projectId: z.string().uuid(), assigneeId: z.string().uuid().nullable().optional(), status: z.enum(["TODO", "IN_PROGRESS", "DONE"]).default("TODO"), priority: z.enum(["LOW", "MEDIUM", "HIGH"]).default("MEDIUM"), dueDate: z.string().datetime().nullable().optional() }), params: z.object({}), query: z.object({}) });
export const taskUpdateSchema = z.object({ body: z.object({ title: z.string().min(2).max(180).optional(), description: z.string().max(1000).optional(), projectId: z.string().uuid().optional(), assigneeId: z.string().uuid().nullable().optional(), status: z.enum(["TODO", "IN_PROGRESS", "DONE"]).optional(), priority: z.enum(["LOW", "MEDIUM", "HIGH"]).optional(), dueDate: z.string().datetime().nullable().optional() }).refine(v => Object.keys(v).length), params, query: z.object({}) });
