import { useEffect, useMemo, useState } from "react";
import { Brain, CheckCircle2, FolderKanban, LogOut, Plus, Search, Sparkles } from "lucide-react";
import { api, getToken, setToken } from "./api.js";

function Auth({ onAuth }) {
  const [mode,setMode]=useState("login"); const [form,setForm]=useState({name:"",email:"",password:""}); const [error,setError]=useState("");
  const submit=async(e)=>{e.preventDefault();setError("");try{const data=await api(`/auth/${mode}`,{method:"POST",body:JSON.stringify(mode==="login"?{email:form.email,password:form.password}:form)});setToken(data.token);onAuth(data.user);}catch(err){setError(err.message)}};
  return <div className="auth-shell"><form className="auth-card" onSubmit={submit}><div className="logo"><Sparkles/> DevFlow AI</div><h1>{mode==="login"?"Welcome back":"Create your workspace"}</h1>{mode==="register"&&<input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<p className="error">{error}</p>}<button>{mode==="login"?"Login":"Register"}</button><a onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Create an account":"Already registered? Login"}</a></form></div>
}

export default function App(){
  const [user,setUser]=useState(null),[projects,setProjects]=useState([]),[tasks,setTasks]=useState([]),[stats,setStats]=useState(null),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[error,setError]=useState(""),[aiBusy,setAiBusy]=useState(false);
  const load=async()=>{try{const [me,p,t,s]=await Promise.all([api("/auth/me"),api("/projects"),api("/tasks"),api("/dashboard")]);setUser(me);setProjects(p);setTasks(t);setStats(s);}catch(e){setToken(null);setUser(null);setError(e.message)}};
  useEffect(()=>{if(getToken())load()},[]);
  const createProject=async()=>{const name=prompt("Project name");if(!name)return;const description=prompt("Project description")||"";await api("/projects",{method:"POST",body:JSON.stringify({name,description})});load()};
  const createTask=async()=>{if(!projects.length)return alert("Create a project first");const title=prompt("Task title");if(!title)return;await api("/tasks",{method:"POST",body:JSON.stringify({title,projectId:projects[0].id,priority:"MEDIUM",status:"TODO"})});load()};
  const toggle=async(task)=>{await api(`/tasks/${task.id}`,{method:"PATCH",body:JSON.stringify({status:task.status==="DONE"?"TODO":"DONE"})});load()};
  const generate=async(project)=>{setAiBusy(true);try{const suggestions=await api("/ai/generate-tasks",{method:"POST",body:JSON.stringify({projectName:project.name,projectDescription:project.description,count:5})});for(const s of suggestions){await api("/tasks",{method:"POST",body:JSON.stringify({title:s.title,description:s.description||"",projectId:project.id,priority:s.priority||"MEDIUM",status:"TODO"})});}await load();}catch(e){alert(e.message)}finally{setAiBusy(false)}};
  const filtered=useMemo(()=>tasks.filter(t=>(status==="ALL"||t.status===status)&&(t.title.toLowerCase().includes(query.toLowerCase())||t.project.name.toLowerCase().includes(query.toLowerCase()))),[tasks,status,query]);
  if(!user)return <Auth onAuth={(u)=>{setUser(u);load()}}/>;
  return <div className="app"><aside><div className="brand"><Sparkles/>DevFlow AI</div><nav><button className="active">Dashboard</button><button>Projects</button><button>Tasks</button></nav><div className="profile"><b>{user.name}</b><span>{user.email}</span><button onClick={()=>{setToken(null);setUser(null)}}><LogOut size={15}/> Logout</button></div></aside><main><header><div><h1>Project command center</h1><p>Plan, track and accelerate work with AI.</p></div><button onClick={createTask}><Plus size={16}/> New task</button></header><section className="search"><Search size={16}/><input placeholder="Search tasks and projects" value={query} onChange={e=>setQuery(e.target.value)}/></section>{error&&<div className="errorbox">{error}</div>}<section className="stats"><article><FolderKanban/><strong>{stats?.projects||0}</strong><span>Projects</span></article><article><CheckCircle2/><strong>{stats?.completedTasks||0}</strong><span>Completed</span></article><article><Brain/><strong>{stats?.completionRate||0}%</strong><span>Completion rate</span></article></section><section className="section-head"><h2>Projects</h2><button onClick={createProject}><Plus size={15}/> Add project</button></section><section className="projects">{projects.map(p=><article key={p.id}><h3>{p.name}</h3><p>{p.description}</p><span>{p.tasks.length} tasks</span><button disabled={aiBusy} onClick={()=>generate(p)}><Sparkles size={14}/> {aiBusy?"Generating...":"AI generate tasks"}</button></article>)}{!projects.length&&<div className="empty">No projects yet. Create your first project.</div>}</section><section className="section-head"><h2>Tasks</h2><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="TODO">Todo</option><option value="IN_PROGRESS">In progress</option><option value="DONE">Done</option></select></section><section className="tasklist">{filtered.map(t=><article key={t.id}><button className={t.status==="DONE"?"check done":"check"} onClick={()=>toggle(t)}>{t.status==="DONE"?"✓":""}</button><div><b>{t.title}</b><span>{t.project.name}</span></div><em className={t.priority.toLowerCase()}>{t.priority}</em><small>{t.status.replace("_"," ")}</small></article>)}{!filtered.length&&<div className="empty">No tasks match your search/filter.</div>}</section></main></div>
}
