import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import users from "./routes/users.js";
import projects from "./routes/projects.js";
import tasks from "./routes/tasks.js";
import { errorHandler, notFound } from "./middleware/errorHandler.js";
export const app=express();
app.use(helmet()); app.use(cors({origin:process.env.CLIENT_ORIGIN||true})); app.use(express.json()); app.use(morgan("dev"));
app.get("/api/health",(req,res)=>res.json({success:true,data:{status:"ok",database:"postgresql"}}));
app.use("/api/users",users); app.use("/api/projects",projects); app.use("/api/tasks",tasks); app.use(notFound); app.use(errorHandler);
