import "dotenv/config";
import express from "express";
import cors from "cors";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { db } from "./db.js";
const app=express();const port=Number(process.env.PORT||4000);const now=()=>new Date().toISOString();const id=p=>`${p}-${randomUUID()}`;
app.use(cors({origin:process.env.CLIENT_ORIGIN||"*"}));app.use(express.json());
const userSchema=z.object({name:z.string().min(2),email:z.string().email(),role:z.string().default("Developer")});
const projectSchema=z.object({name:z.string().min(2),description:z.string().default(""),ownerId:z.string(),status:z.enum(["active","paused","completed"]).default("active")});
const taskSchema=z.object({projectId:z.string(),assigneeId:z.string().nullable().optional(),title:z.string().min(2),description:z.string().default(""),status:z.enum(["todo","in-progress","done"]).default("todo"),priority:z.enum(["low","medium","high"]).default("medium"),dueDate:z.string().nullable().optional()});
const parse=(s,b)=>{const r=s.safeParse(b);if(!r.success){const e=new Error("Validation failed");e.status=400;e.details=r.error.flatten();throw e}return r.data};
const must=(sql,args,label)=>{const row=db.prepare(sql).get(...args);if(!row){const e=new Error(`${label} not found`);e.status=404;throw e}return row};
app.get("/api/health",(req,res)=>res.json({status:"ok",task:3,database:"SQLite",persistence:true}));
app.get("/api/users",(req,res)=>res.json(db.prepare("SELECT * FROM users ORDER BY created_at DESC").all()));
app.post("/api/users",(req,res)=>{const d=parse(userSchema,req.body),uid=id("u"),ts=now();db.prepare("INSERT INTO users VALUES(?,?,?,?,?)").run(uid,d.name,d.email,d.role,ts);res.status(201).json(must("SELECT * FROM users WHERE id=?",[uid],"User"))});
app.patch("/api/users/:id",(req,res)=>{const c=must("SELECT * FROM users WHERE id=?",[req.params.id],"User"),d=parse(userSchema.partial(),req.body);db.prepare("UPDATE users SET name=?,email=?,role=? WHERE id=?").run(d.name??c.name,d.email??c.email,d.role??c.role,req.params.id);res.json(must("SELECT * FROM users WHERE id=?",[req.params.id],"User"))});
app.delete("/api/users/:id",(req,res)=>{must("SELECT * FROM users WHERE id=?",[req.params.id],"User");db.prepare("DELETE FROM users WHERE id=?").run(req.params.id);res.status(204).end()});
app.get("/api/projects",(req,res)=>res.json(db.prepare("SELECT p.*,COUNT(t.id) task_count,SUM(CASE WHEN t.status='done' THEN 1 ELSE 0 END) done_count FROM projects p LEFT JOIN tasks t ON t.project_id=p.id GROUP BY p.id ORDER BY p.created_at DESC").all()));
app.get("/api/projects/:id",(req,res)=>{const p=must("SELECT * FROM projects WHERE id=?",[req.params.id],"Project");res.json({...p,tasks:db.prepare("SELECT * FROM tasks WHERE project_id=?").all(req.params.id)})});
app.post("/api/projects",(req,res)=>{const d=parse(projectSchema,req.body);must("SELECT id FROM users WHERE id=?",[d.ownerId],"Owner");const pid=id("p"),ts=now();db.prepare("INSERT INTO projects VALUES(?,?,?,?,?,?,?)").run(pid,d.name,d.description,d.ownerId,d.status,ts,ts);res.status(201).json(must("SELECT * FROM projects WHERE id=?",[pid],"Project"))});
app.patch("/api/projects/:id",(req,res)=>{const c=must("SELECT * FROM projects WHERE id=?",[req.params.id],"Project"),d=parse(projectSchema.partial(),req.body);db.prepare("UPDATE projects SET name=?,description=?,owner_id=?,status=?,updated_at=? WHERE id=?").run(d.name??c.name,d.description??c.description,d.ownerId??c.owner_id,d.status??c.status,now(),req.params.id);res.json(must("SELECT * FROM projects WHERE id=?",[req.params.id],"Project"))});
app.delete("/api/projects/:id",(req,res)=>{must("SELECT * FROM projects WHERE id=?",[req.params.id],"Project");db.prepare("DELETE FROM projects WHERE id=?").run(req.params.id);res.status(204).end()});
app.get("/api/tasks",(req,res)=>res.json(db.prepare("SELECT t.*,p.name project_name,u.name assignee_name FROM tasks t JOIN projects p ON p.id=t.project_id LEFT JOIN users u ON u.id=t.assignee_id ORDER BY t.created_at DESC").all()));
app.post("/api/tasks",(req,res)=>{const d=parse(taskSchema,req.body);must("SELECT id FROM projects WHERE id=?",[d.projectId],"Project");const tid=id("t"),ts=now();db.prepare("INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?,?,?)").run(tid,d.projectId,d.assigneeId??null,d.title,d.description,d.status,d.priority,d.dueDate??null,ts,ts);res.status(201).json(must("SELECT * FROM tasks WHERE id=?",[tid],"Task"))});
app.patch("/api/tasks/:id",(req,res)=>{const c=must("SELECT * FROM tasks WHERE id=?",[req.params.id],"Task"),d=parse(taskSchema.partial(),req.body);db.prepare("UPDATE tasks SET project_id=?,assignee_id=?,title=?,description=?,status=?,priority=?,due_date=?,updated_at=? WHERE id=?").run(d.projectId??c.project_id,d.assigneeId!==undefined?d.assigneeId:c.assignee_id,d.title??c.title,d.description??c.description,d.status??c.status,d.priority??c.priority,d.dueDate!==undefined?d.dueDate:c.due_date,now(),req.params.id);res.json(must("SELECT * FROM tasks WHERE id=?",[req.params.id],"Task"))});
app.delete("/api/tasks/:id",(req,res)=>{must("SELECT * FROM tasks WHERE id=?",[req.params.id],"Task");db.prepare("DELETE FROM tasks WHERE id=?").run(req.params.id);res.status(204).end()});
app.use((req,res)=>res.status(404).json({error:{message:"Route not found"}}));app.use((e,req,res,next)=>res.status(e.status||500).json({error:{message:e.status?e.message:"Internal server error",details:e.details}}));
app.listen(port,()=>console.log(`Task 3 persistent API: http://localhost:${port}`));
